#ifndef TINYSTLBYCIEL_INCLUDE_CIEL_CONCEPTS_IMPL_RANGES_SWAP_H_
#define TINYSTLBYCIEL_INCLUDE_CIEL_CONCEPTS_IMPL_RANGES_SWAP_H_

#include <ciel/algorithm.h>

namespace ciel {

}   //namespace ciel

#endif //TINYSTLBYCIEL_INCLUDE_CIEL_CONCEPTS_IMPL_RANGES_SWAP_H_
