#ifndef TINYSTLBYCIEL_INCLUDE_CIEL_ITERATOR_IMPL_INPUT_ITERATOR_H_
#define TINYSTLBYCIEL_INCLUDE_CIEL_ITERATOR_IMPL_INPUT_ITERATOR_H_

namespace ciel {



}   //namespace ciel

#endif //TINYSTLBYCIEL_INCLUDE_CIEL_ITERATOR_IMPL_INPUT_ITERATOR_H_
